src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'string', length: 255)]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    private $address;

    #[ORM\Column(type: 'string', length: 255)]
    private $mail;

    #[ORM\Column(type: 'string', length: 32)]
    private $roles;

    #[ORM\Column(type: 'datetime')]
    private $last_login;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Orders::class)]
    private $orders;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getRoles(): array
    {
        return [$this->roles];
    }

    public function setRoles(string $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getLastLogin(): ?\DateTimeInterface
    {
        return $this->last_login;
    }

    public function setLastLogin(\DateTimeInterface $last_login): self
    {
        $this->last_login = $last_login;

        return $this;
    }

    /**
     * @return Collection|Orders[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Orders $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setUser($this);
        }

        return $this;
    }

    public function removeOrder(Orders $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getUserIdentifier(): string
    {
        return $this->getMail();
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('password', PasswordType::class)
            ->add('address')
            ->add('mail', EmailType::class)
            //->add('roles')
            //->add('last_login')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use
    Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $passwordHasher): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $user->setRoles('ROLE_USER');

            $plaintextPassword = $user->getPassword();
            $hashedPassword = $passwordHasher->hashPassword(
                $user,
                $plaintextPassword
            );
            $user->setPassword($hashedPassword);

            $user->setLastLogin(new \DateTime('now'));
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('login', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager, UserPasswordHasherInterface $passwordHasher): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $plaintextPassword = $user->getPassword();
            $hashedPassword = $passwordHasher->hashPassword(
                $user,
                $plaintextPassword
            );
            $user->setPassword($hashedPassword);

            $entityManager->flush();

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-secondary btn-lg" tabindex="-1" role="button">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}

<form class="row gy-2 gx-3 align-items-center">
  <div class="col-auto mb-3">
    <label for="formName" class="form-label">Pseudo</label>
    {{ form_widget(form.name, {'attr': {'class': 'form-control'}}) }}
  </div>
  <div class="col-auto mb-3">
    <label for="formEmail" class="form-label">Adresse email</label>
    {{ form_widget(form.mail, {'attr': {'class': 'form-control'}}) }}
  </div>
  <div class="col-auto mb-3">
    <label for="formPassword" class="form-label">Mot de passe</label>
    {{ form_widget(form.password, {'attr': {'class': 'form-control'}}) }}
  </div>
  <div class="col-auto mb-3">
    <label for="formAddress" class="form-label">Adresse postale</label>
    {{ form_widget(form.address, {'attr': {'class': 'form-control', 'placeholder': '1 Rue de lexemple 12345'}}) }}
  </div>

  <div class="d-flex justify-content-center">
    <button type="submit" class="btn btn-secondary btn-lg">S'inscrire</button>
  </div>

</form>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

{#    <a href="{{ path('user_index') }}">back to list</a>#}
    {% if is_granted('ROLE_ADMIN') %}
    {{ include('user/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

<div class="table-responsive container ">
    <table class="table table-dark table-sm w-auto table-hover table-striped table-bordered">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Password</th>
                <th>Address</th>
                <th>Mail</th>
                <th>Roles</th>
                <th>Last_login</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.address }}</td>
                <td>{{ user.mail }}</td>
                <td>
                    {% for roles in user.roles %}
                    {{ roles }}
                    {% endfor %}
                </td>
                <td>{{ user.lastLogin ? user.lastLogin|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}" class="btn btn-secondary btn-lg" tabindex="-1" role="button" aria-disabled="true">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}" class="btn btn-secondary btn-lg" tabindex="-1" role="button" aria-disabled="true">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div style="text-align: center;margin-top: 5px;">
    <a href="{{ path('user_new') }}" class="btn btn-secondary btn-lg" tabindex="-1" role="button" aria-disabled="true">Create new</a>
</div>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription{% endblock %}

{% block body %}
    <h1>Inscription</h1>

    <div class="d-flex justify-content-center">
        {{ include('user/_form.html.twig') }}
    </div>

{#    <a href="{{ path('user_index') }}">back to list</a>#}
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

<div class="table-responsive container ">
    <table class="table table-dark table-sm w-auto table-hover table-striped table-bordered">
        <tbody>
        {% if is_granted('ROLE_ADMIN') %}
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
        {% endif %}
            <tr>
                <th>Name</th>
                <td>{{ user.name }}</td>
            </tr>
        {% if is_granted('ROLE_ADMIN') %}
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
        {% endif %}
            <tr>
                <th>Address</th>
                <td>{{ user.address }}</td>
            </tr>
            <tr>
                <th>Mail</th>
                <td>{{ user.mail }}</td>
            </tr>
        {% if is_granted('ROLE_ADMIN') %}
            <tr>
                <th>Roles</th>
                <td>
                    {% for roles in user.roles %}
                        {{ roles }}
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th>Last_login</th>
                <td>{{ user.lastLogin ? user.lastLogin|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        {% endif %}
        </tbody>
    </table>
</div>

    <div style="text-align: center;margin-top: 5px;">
        <a href="{{ path('user_edit', {'id': user.id}) }}" class="btn btn-secondary btn-lg" tabindex="-1" role="button" aria-disabled="true">Edit</a>
    </div>

    {% if is_granted('ROLE_ADMIN') %}
    <div style="text-align: center;margin-top: 5px;">
        <a href="{{ path('user_index')}}" class="btn btn-secondary btn-lg" tabindex="-1" role="button" aria-disabled="true">Tout les user</a>
        <a href="{{ path('category_index')}}" class="btn btn-secondary btn-lg" tabindex="-1" role="button" aria-disabled="true">Toutes les categories</a>
    </div>
    {% endif %}
{#    <a href="{{ path('user_index') }}">back to list</a>#}

{#    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>#}
{#    {% if is_granted('ROLE_ADMIN') %}
        <div style="text-align: center;margin-top: 5px;">
            <a href="{{ include('user/_delete_form.html.twig') }}" class="btn btn-secondary btn-lg" tabindex="-1" role="button" aria-disabled="true">Suppr</a>
            {{ include('user/_delete_form.html.twig') }}
        </div>

    {% endif %}#}
{% endblock %}